# --------------------------------
# 共通設定
# --------------------------------

# tmux起動時のシェルをzshにする
set-option -g default-shell /bin/zsh

# tmuxを256色表示できるようにする
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

# tmux上でnvimを使うと文字が残ることがあるため設定
set-option -ga terminal-overrides ',xterm-256color:Tc'

# ---------------------------------
# Key bindings
# ---------------------------------

# prefixキーをC-qに変更
set -g prefix C-q

# C-bのキーバインドを解除
unbind C-b

# vimのキーバインドでペインを移動する
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# vimのキーバインドでペインをリサイズする
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# | でペインを縦分割する
bind | split-window -h

# - でペインを縦分割する
bind - split-window -v

# 番号基準値を変更
set-option -g base-index 1

# マウス操作を有効にする
set-option -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

# コピーモードを設定する
# コピーモードでvimキーバインドを使う
setw -g mode-keys vi

# 'v' で選択を始める
bind -T copy-mode-vi v send -X begin-selection

# 'V' で行選択
bind -T copy-mode-vi V send -X select-line

# 'C-v' で矩形選択
bind -T copy-mode-vi C-v send -X rectangle-toggle

# 'y' でヤンク
bind -T copy-mode-vi y send -X copy-selection

# 'Y' で行ヤンク
bind -T copy-mode-vi Y send -X copy-line

# 'C-p'でペースト
bind-key C-p paste-buffer

set -g display-panes-time 3000

set -s escape-time 0

# ---------------------------------
# テーマ設定
# ---------------------------------

# ステータスバーは下部で固定
set-option -g status-position bottom

# ステータスバーの背景色・文字色を指定
set -g status-style "bg=default,fg=white"

# status line を更新する間隔を 1 秒にする
set-option -g status-interval 1

# 左側ステータス表示のスタイル
set -g status-left '👻 tmux : '

# 右側ステータス表示のスタイル
# 何も表示しない
set -g status-right ''

# ペインのフォーマット
set -g window-status-format "#I.#W "
set -g window-status-current-format "▼ #I.#W "
 
# for claude code
# https://code.claude.com/docs/en/terminal-config#configure-tmux
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
